# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66399783701a782755da8e99943c5d23c1c9cb721f2e224246da5613a1a2f12aaff98e30bcd4d89fc70bd119564527357f1849c7e4ce0dee4c1aef781840ce8

test:
  secret_key_base: 0023416b16346c514f2e7306be70453de6cef9ce96fd71f20b34135e3338e3657a032f01e59823a179182469c013022ae273486f9a19196b23ba40d9f689ffd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
