# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611ae0bffa9a8ec14fe7dea0dab2d358940021ab2191111211be8e3a98af74eef11badd34f2047a6e629327a159b9eca186fe406e6448468c77e891bf9c416f3

test:
  secret_key_base: 357649c9fffc7892566882527ad9a196606aa2ec41f795ecac056e1a4850b00f9f21ae1a95354824a6693793497024c50a550752c1b962bd84b9b644bd3a2ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
